### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by bendavies**
Hi,

I've updated your dependencies.
guzzle 3 wasn't used and i've updated the oauth-subscriber

### CODE REVIEW

**Comment by stevenmaguire** [comment]
Great. Thank you. 

It is not that `guzzle` is not being used, more so that the `oauth-subscriber` package manages its own dependancies which include `guzzle`.

Thanks for catching this and for the PR.

**Comment by bendavies** [comment]
No problem!. 
`guzzlehttp/oauth-subscriber` uses `guzzlehttp/guzzle` rather than `guzzle/guzzle`

Cheers!

**Comment by bendavies** [comment]
By the way, if you could tag a minor release that would be great! Thanks

**Comment by stevenmaguire** [comment]
@bendavies 1.3.0 is out.

**Comment by bendavies** [comment]
thanks!

**Pull request merged**
